//
//  ZHHUIKit.h
//  ZHHAnneKit
//
//  Created by 桃色三岁 on 2022/9/14.
//  Copyright © 2022 桃色三岁. All rights reserved.
//

#ifndef ZHHUIKit_h
#define ZHHUIKit_h

#if __has_include(<ZHHAnneKit/ZHHUIKit.h>)
#import <ZHHAnneKit/UIApplication+ZHHKeyboardFrame.h>
#import <ZHHAnneKit/UIBarButtonItem+ZHHExtend.h>
#import <ZHHAnneKit/UIBarButtonItem+ZHHAction.h>
#import <ZHHAnneKit/UIButton+ZHHBackgroundColor.h>
#import <ZHHAnneKit/UIButton+ZHHButtonBlock.h>
#import <ZHHAnneKit/UIButton+ZHHContentLayout.h>
#import <ZHHAnneKit/UIButton+ZHHCountDown.h>
#import <ZHHAnneKit/UIButton+ZHHEmitter.h>
#import <ZHHAnneKit/UIButton+ZHHExtend.h>
#import <ZHHAnneKit/UIButton+ZHHImagePosition.h>
#import <ZHHAnneKit/UIButton+ZHHIndicator.h>
#import <ZHHAnneKit/UIButton+ZHHTouchAreaInsets.h>
#import <ZHHAnneKit/UIColor+ZHHGradient.h>
#import <ZHHAnneKit/UIColor+ZHHHex.h>
#import <ZHHAnneKit/UIControl+ZHHControl.h>
#import <ZHHAnneKit/UIControl+ZHHSound.h>
#import <ZHHAnneKit/UIDevice+ZHHHardware.h>
#import <ZHHAnneKit/UIFont+ZHHAdapter.h>
#import <ZHHAnneKit/UIImage+ZHHAlpha.h>
#import <ZHHAnneKit/UIImage+ZHHBetterFace.h>
#import <ZHHAnneKit/UIImage+ZHHCapture.h>
#import <ZHHAnneKit/UIImage+ZHHColor.h>
#import <ZHHAnneKit/UIImage+ZHHCompress.h>
#import <ZHHAnneKit/UIImage+ZHHCut.h>
#import <ZHHAnneKit/UIImage+ZHHFileName.h>
#import <ZHHAnneKit/UIImage+ZHHExtend.h>
#import <ZHHAnneKit/UIImage+ZHHMask.h>
#import <ZHHAnneKit/UIImage+ZHHMerge.h>
#import <ZHHAnneKit/UIImage+ZHHNameImage.h>
#import <ZHHAnneKit/UIImage+ZHHOrientation.h>
#import <ZHHAnneKit/UIImage+ZHHQRCode.h>
#import <ZHHAnneKit/UIImage+ZHHResize.h>
#import <ZHHAnneKit/UIImage+ZHHURLSize.h>
#import <ZHHAnneKit/UILabel+ZHHEdgeInsets.h>
#import <ZHHAnneKit/UILabel+ZHHExtend.h>
#import <ZHHAnneKit/UILabel+ZHHTextAlignment.h>
#import <ZHHAnneKit/UILabel+ZHHTextTapAction.h>
#import <ZHHAnneKit/UINavigationBar+ZHHExtend.h>
#import <ZHHAnneKit/UINavigationController+ZHHStackManager.h>
#import <ZHHAnneKit/UINavigationController+ZHHTransitions.h>
#import <ZHHAnneKit/UINavigationItem+ZHHExtend.h>
#import <ZHHAnneKit/UINavigationItem+ZHHLoading.h>
#import <ZHHAnneKit/UIScreen+ZHHExtend.h>
#import <ZHHAnneKit/UISlider+ZHHExtend.h>
#import <ZHHAnneKit/UISplitViewController+ZHHQuickAccess.h>
#import <ZHHAnneKit/UITabBar+ZHHExtend.h>
#import <ZHHAnneKit/UITableView+ZHHExtend.h>
#import <ZHHAnneKit/UITableView+ZHHiOS7Style.h>
#import <ZHHAnneKit/UITableViewHeaderFooterView+ZHHExtend.h>
#import <ZHHAnneKit/UITextField+ZHHCustomView.h>
#import <ZHHAnneKit/UITextField+ZHHExtend.h>
#import <ZHHAnneKit/UITextField+ZHHSelect.h>
#import <ZHHAnneKit/UITextField+ZHHShake.h>
#import <ZHHAnneKit/UIView+ZHHAnimation.h>
#import <ZHHAnneKit/UIView+ZHHBlockGesture.h>
#import <ZHHAnneKit/UIView+ZHHCustomBorder.h>
#import <ZHHAnneKit/UIView+ZHHExtend.h>
#import <ZHHAnneKit/UIView+ZHHFind.h>
#import <ZHHAnneKit/UIView+ZHHFrame.h>
#import <ZHHAnneKit/UIView+ZHHRectCorner.h>
#import <ZHHAnneKit/UIView+ZHHScreenshot.h>
#import <ZHHAnneKit/UIView+ZHHShake.h>
#import <ZHHAnneKit/UIView+ZHHVisuals.h>
#import <ZHHAnneKit/UIViewController+ZHHFullScreen.h>
#import <ZHHAnneKit/UIViewController+ZHHStatusBarStyle.h>
#import <ZHHAnneKit/UIViewController+ZHHExtend.h>
#import <ZHHAnneKit/UIWindow+ZHHHierarchy.h>
#else
#import "UIApplication+ZHHKeyboardFrame.h""
#import "UIBarButtonItem+ZHHExtend.h""
#import "UIBarButtonItem+ZHHAction.h"
#import "UIButton+ZHHBackgroundColor.h"
#import "UIButton+ZHHButtonBlock.h"
#import "UIButton+ZHHContentLayout.h"
#import "UIButton+ZHHCountDown.h"
#import "UIButton+ZHHEmitter.h"
#import "UIButton+ZHHExtend.h"
#import "UIButton+ZHHImagePosition.h"
#import "UIButton+ZHHIndicator.h"
#import "UIButton+ZHHTouchAreaInsets.h"
#import "UIColor+ZHHGradient.h"
#import "UIColor+ZHHHex.h"
#import "UIControl+ZHHControl.h"
#import "UIControl+ZHHSound.h"
#import "UIDevice+ZHHHardware.h"
#import "UIFont+ZHHAdapter.h"
#import "UIImage+ZHHAlpha.h"
#import "UIImage+ZHHBetterFace.h"
#import "UIImage+ZHHCapture.h"
#import "UIImage+ZHHColor.h"
#import "UIImage+ZHHCompress.h"
#import "UIImage+ZHHCut.h"
#import "UIImage+ZHHFileName.h"
#import "UIImage+ZHHExtend.h"
#import "UIImage+ZHHMask.h"
#import "UIImage+ZHHMerge.h"
#import "UIImage+ZHHNameImage.h"
#import "UIImage+ZHHOrientation.h"
#import "UIImage+ZHHQRCode.h"
#import "UIImage+ZHHResize.h"
#import "UIImage+ZHHURLSize.h"
#import "UILabel+ZHHEdgeInsets.h"
#import "UILabel+ZHHExtend.h"
#import "UILabel+ZHHTextAlignment.h"
#import "UILabel+ZHHTextTapAction.h"
#import "UINavigationBar+ZHHExtend.h"
#import "UINavigationController+ZHHStackManager.h"
#import "UINavigationController+ZHHTransitions.h"
#import "UINavigationItem+ZHHExtend.h"
#import "UINavigationItem+ZHHLoading.h"
#import "UIScreen+ZHHExtend.h"
#import "UISlider+ZHHExtend.h"
#import "UISplitViewController+ZHHQuickAccess.h"
#import "UITabBar+ZHHExtend.h"
#import "UITableView+ZHHExtend.h"
#import "UITableView+ZHHiOS7Style.h"
#import "UITableViewHeaderFooterView+ZHHExtend.h"
#import "UITextField+ZHHCustomView.h"
#import "UITextField+ZHHExtend.h"
#import "UITextField+ZHHSelect.h"
#import "UITextField+ZHHShake.h"
#import "UIView+ZHHAnimation.h"
#import "UIView+ZHHBlockGesture.h"
#import "UIView+ZHHCustomBorder.h"
#import "UIView+ZHHExtend.h"
#import "UIView+ZHHFind.h"
#import "UIView+ZHHFrame.h"
#import "UIView+ZHHRectCorner.h"
#import "UIView+ZHHScreenshot.h"
#import "UIView+ZHHShake.h"
#import "UIView+ZHHVisuals.h"
#import "UIViewController+ZHHFullScreen.h"
#import "UIViewController+ZHHStatusBarStyle.h"
#import "UIViewController+ZHHExtend.h"
#import "UIWindow+ZHHHierarchy.h"
#endif

#endif /* ZHHUIKit_h */
